sudo: false
language: android
jdk: oraclejdk8
script: ./gradlew clean build

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
    email: true