sudo: false
language: android
jdk: oraclejdk8
script: ./gradlew clean build

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
    email: true